php:
  build: .
  links:
    - mysql
    - elasticsearch
    - rabbit
  entrypoint:
    sh /entrypoint.sh
  volumes:
    - ./entrypoint.sh:/entrypoint.sh
    - ../:/var/www/shop

mysql:
  image: mysql:8.0.0
  environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=true

nginx:
  image: nginx:1.11.4
  links:
    - php
  volumes_from:
    - php
  volumes:
    - ./vhost.conf:/etc/nginx/conf.d/default.conf
  ports:
    - "80:80"

elasticsearch:
  image: elasticsearch:2.4
  ports:
    - "9200:9200"
    - "9300:9300"

rabbit:
  image: rabbitmq:3-management
  ports:
    - 15672:15672
    - 5672:5672
